export enum ActionTypes {
  INIT = 'INIT',
  SIGN_UP = 'SIGN_UP',
  LOG_IN = 'LOG_IN',
  LOG_OFF = 'LOG_OFF',
  GET_IMAGES = 'GET_IMAGES',
  ON_SAVE_IMAGE = 'ON_SAVE_IMAGE',
  GET_USER_INFO = 'GET_USER_INFO',
  SET_USER_INFO = 'SET_USER_INFO',
}
