export enum MutationTypes {
  SET_USER_ID = 'SET_USER_ID',
  SET_IMAGES = 'SET_IMAGES',
  SET_ACTIVE_TOOL = 'SET_ACTIVE_TOOL',
  SET_LINE_COLOR = 'SET_LINE_COLOR',
  SET_LINE_WIDTH = 'SET_LINE_WIDTH',
  SET_SHOW_LOADER = 'SET_SHOW_LOADER',
  SET_WALKTHROUGH = 'SET_WALKTHROUGH',
}
